# Default values for qnap-trident.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

tridentOperator:
  image: qnapsystem/qnap-csi-operator:v1.5.2
  cgiServerImage : qnapsystem/qnap-csi-backend-qts-sidecar:v1.5.2
  imagePullPolicy: IfNotPresent
  logLevel: debug

tridentOrchestrator:
  image: qnapsystem/qnap-csi:v1.5.2
  debug: true

# forceInstallRancherClusterRoles will install a Rancher specific ClusterRole and ClusterRoleBinding when set to true.
# When set to false, the ClusterRole and ClusterRoleBinding will be installed only when a Rancher cluster is detected. 
forceInstallRancherClusterRoles: false